### PR TITLE
ENH: save/load scipy.sparce.csr_matrix

### PR DESCRIPTION
**Pull request by kingjr**
closes https://github.com/h5io/h5io/issues/16

### CODE REVIEW

**Comment by kingjr** [comment]
why isn't coveralls happy?

**Comment by Eric89GXL** [comment]
> Coverage decreased (-0.2%) to 97.313%

You could look at the report to find out, but I suspect it's because you added some `raise` lines that are never touched. They are too difficult to test, thuough, so it's fine.

**Comment by Eric89GXL** [comment]
Thanks @kingjr

**Comment by drammock** [comment]
a decrease of 0.2% is not worth worrying about.  It's probably because of [line 275](https://coveralls.io/builds/6517837/source?filename=h5io%2F_h5io.py#L275) and 283, which I think would require setting up a separate Travis job without scipy installed, which is dumb.

**Comment by drammock** [comment]
@Eric89GXL you beat me to the answer by 22 seconds!

**Comment by kingjr** [comment]
Ok, I think I still need to learn how to parse the coverall reports...

**Pull request merged**
