### PR TITLE
Allow reading and writing to open h5py.File objects

### PR DESCRIPTION
**Pull request by pmrv**
As discussed in #56.  I've added additional errors in case the file is opened with wrong modes.

### CODE REVIEW

**Comment by drammock** [comment]
### CI failures

#### Travis:

```
$ make flake
Running flake8
h5io/_h5io.py:101:80: E501 line too long (81 > 79 characters)
h5io/_h5io.py:102:29: E128 continuation line under-indented for visual indent
h5io/_h5io.py:104:15: F821 undefined name 'UnsupportedOperation'
h5io/_h5io.py:112:5: E306 expected 1 blank line before a nested definition, found 0
h5io/_h5io.py:276:15: F821 undefined name 'UnsupportedOperation'
h5io/_h5io.py:276:80: E501 line too long (80 > 79 characters)
h5io/_h5io.py:281:5: E306 expected 1 blank line before a nested definition, found 0
h5io/tests/test_io.py:86:1: E302 expected 2 blank lines, found 1
h5io/tests/test_io.py:92:10: F821 undefined name 'h5py'
h5io/tests/test_io.py:97:10: F821 undefined name 'h5py'
h5io/tests/test_io.py:98:23: F821 undefined name 'UnsupportedOperation'
h5io/tests/test_io.py:100:10: F821 undefined name 'h5py'
h5io/tests/test_io.py:101:23: F821 undefined name 'UnsupportedOperation'
h5io/tests/test_io.py:103:10: F821 undefined name 'h5py'
h5io/tests/test_io.py:105:80: E501 line too long (80 > 79 characters)
h5io/tests/test_io.py:109:1: E303 too many blank lines (3)
16
Makefile:38: recipe for target 'flake' failed
```

#### Appveyor

```
================================== FAILURES ===================================
_____________________________ test_h5_file_object _____________________________

tmpdir = local('C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_h5_file_object0')

    def test_h5_file_object(tmpdir):
        tempdir = str(tmpdir)
        test_file_path = op.join(tempdir, 'test1.hdf5')
        # test that wrong object type raises error
        pytest.raises(ValueError, write_hdf5, fname=33, data=1)
        # test that reading/writing are unaffected
>       with h5py.File(test_file_path, 'a') as test_file_obj:
E       NameError: name 'h5py' is not defined

tempdir    = 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_h5_file_object0'
test_file_path = 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_h5_file_object0\\test1.hdf5'
tmpdir     = local('C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_h5_file_object0')

h5io\tests\test_io.py:92: NameError
```

#### Appveyor Windows
```
================================== FAILURES ===================================
_____________________________ test_h5_file_object _____________________________

tmpdir = local('C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_h5_file_object0')

    def test_h5_file_object(tmpdir):
        tempdir = str(tmpdir)
        test_file_path = op.join(tempdir, 'test1.hdf5')
        # test that wrong object type raises error
        pytest.raises(ValueError, write_hdf5, fname=33, data=1)
        # test that reading/writing are unaffected
>       with h5py.File(test_file_path, 'a') as test_file_obj:
E       NameError: name 'h5py' is not defined

tempdir    = 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_h5_file_object0'
test_file_path = 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_h5_file_object0\\test1.hdf5'
tmpdir     = local('C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_h5_file_object0')

h5io\tests\test_io.py:92: NameError
```

**Comment by pmrv** [comment]
Sorry this somehow got lost in my notifications.  I can't seem to test locally, so let's hope this works out.

**Comment by larsoner** [comment]
Thanks @pmrv -- I did some local iteration until things were green, hopefully my changes make sense!

**Comment by pmrv** [comment]
Looks good, thanks for merging this!

**Pull request merged**
