### PR TITLE
Update _version.py

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Comment by jan-janssen** [comment]
@larsoner Can you release a new version? Alternatively, I could also do it. As far as I understand it only requires creating a new tag named `h5io-0.2.0` and then the pypi package is build automatically, correct?

**Comment by larsoner** [comment]
Yeah cutting a release should automatically take care of it, which I've now done!

**Comment by jan-janssen** [comment]
@larsoner Thanks a lot, I saw that you created https://github.com/h5io/h5io/releases/tag/h5io-0.1.11 but I am a bit confused about the numbering, should not it be `0.2.0` as defined in the `_version.py`.

**Comment by larsoner** [comment]
Yes that was a mistake so I just also created 0.2.0 right afterward. Could delete the 0.1.11 if we want

**Pull request merged**
