### PR TITLE
read_hdf(): Remove print of file mode

### PR DESCRIPTION
**Pull request by jan-janssen**
This came with https://github.com/h5io/h5io/pull/57 but I do not think it is necessary. 

@pmrv : Is it ok to remove this print statement?

### CODE REVIEW

**Comment by larsoner** [comment]
Agreed that's cruft, thanks @jan-janssen !

**Comment by pmrv** [comment]
Yes, that just slipped through, sorry!

**Comment by jan-janssen** [comment]
@larsoner Can you release a new version of `h5io`? The print is rather annoying when using open files.

**Comment by larsoner** [comment]
After modernizing CIs a bit, release made and auto-pushed to PyPI

https://github.com/h5io/h5io/releases/tag/h5io-0.1.10
https://github.com/h5io/h5io/actions/runs/7290207877
https://pypi.org/project/h5io/0.1.10/

**Pull request merged**
